### ISSUE TITLE
RequestBodyAdvice没有打印请求信息。

### ISSUE THREAD

**Issue by umeitime** [qchery/funda#1]
afterBodyRead里面的log没有输出结果。

ResponseBodyAdvice里面是可以正常打印的。

**Comment by qchery** [comment]
LogRequestBodyAdvice 只处理参数形式为 @RequestBody 的输入，对于 @RequestParam 之类的不会输出，请检查参数的具体形式

![image](https://user-images.githubusercontent.com/11956226/35183719-4a85e922-fdb0-11e7-8e1f-216e68efc7c8.png)

**Comment by umeitime** [comment]
@qchery 是这个原因，但是我的接口没有参数呢？

**Comment by qchery** [comment]
@umeitime 没有参数自然就没有使用 \@RequestBody 注解，肯定不会输出请求的信息
